### ISSUE TITLE
Where to find resources/big_buck_bunny_1080p_24fps_h264.ts ?

### ISSUE THREAD

**Issue by lu-zero** [dholroyd/mpeg2ts-reader#24]
It can be created from the official sources, it would nice to add a scripts to produce it on demand.

**Comment by dholroyd** [comment]
`ffmpeg -i https://download.blender.org/demo/movies/BBB/bbb_sunflower_1080p_30fps_normal.mp4 -c copy resources/big_buck_bunny_1080p_h264.ts` is pretty slow for me.  Do you know of a better mirror?  Or have you maybe seen better test mpegts for download.  The benchmark currently only uses the first ~40Mb of the file in any case.

**Comment by lu-zero** [comment]
Given that the content is not important ideally it can be created from scratch programmatically maybe...

**Comment by dholroyd** [comment]
I will update the error in `bench.rs` to suggest running,

```
ffmpeg -f lavfi -i testsrc=duration=20:size=640x360:rate=30,noise=alls=20:allf=t+u -f lavfi -i "sine=duration=20:frequency=1:beep_factor=480:sample_rate=48000" -c:v libx264 -b:v 20M -map 0:v -c:a aac -b:a 128k -map 1:a -vf format=yuv420p -f mpegts resources/testsrc.ts
```
